name: trunk

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: trunk-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  trunk:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - uses: trunk-io/trunk-action@v1
